### ISSUE TITLE
Player moves weird

### ISSUE THREAD

**Issue by Memorix101** [nadako/HaxeQuake#10]
I don't know why, but since the last update the player is kind of slipping like on ice, walking very slow and jumping doesn't work :/ I tried to fix it myself, but I couldn't figure out the issue yet. Just wanted to report it to you :) 

https://youtu.be/OBahQg9gBtA

**Comment by nadako** [comment]
That's weird because it moves okay here: http://nadako.github.io/HaxeQuake/Client/WebQuake.htm
Do you have any errors in the chrome console?

**Comment by Memorix101** [comment]
That's all. Any ideas why this happens ? It doesn't matter if I run it in Chrome or Firefox :/

Here you can test it yourself:
https://dl.dropboxusercontent.com/u/42689244/Example/HaxeQuake-gh-pages/Client/WebQuake.htm

![screenshot 231](https://cloud.githubusercontent.com/assets/1466920/12436364/e0e7bd00-bf14-11e5-9c8a-0b869e127fbf.png)

**Comment by nadako** [comment]
I can reproduce this with Haxe 3.2.1 instead of dev, maybe there's some problem in the compiler then. Will investigate, thanks!

**Comment by nadako** [comment]
Hmm, was it working for you at all at 3.2.1? Because it couldn't even compile before 4479d7bd4ed9fd36d39df4746c67165631bf8cb6, and the problem still reproduces there.

**Comment by Memorix101** [comment]
I can compile it with 3.2.1 since you changed it, but I get always this weird movment issue.

**Comment by nadako** [comment]
Hmm, by looking at the diff, I found out that 3.2.1 doesn't generate assign operators (like `^=`) on abstracts at all, which i think is the problem. I'll see what can be done.

**Comment by nadako** [comment]
does removing `-D analyzer` from build.hxml file helps, btw?

**Comment by nadako** [comment]
Okay, it looks like haxe 3.2.1 has a bug regarding abstract operators used in conjunction with `set` propertes, resulting in invalid code generation. Latest dev haxe doesn't have that bug, so maybe I should just drop support for 3.2.1... I'll try looking for a workaround though.

Code to reproduce:

``` haxe
abstract A(Int) {
    public function new() this = 1;
    @:op(a+b) static function _(a:A, b:A):A;
}

class Test {
    static var a(default,set):A;
    static function set_a(v:A):A return a = v;
    static function main() {
        a = new A();
        a += a;
        trace(a);
    }
}
```

**Comment by Memorix101** [comment]
When I'm home I'll install a dev build and test it. :) Thank you so much for your help :) I know so many people who wouldn't care ... :)

**Comment by Memorix101** [comment]
Well, I installed the latest Dev Build from build.haxe.org, it works now. But there sound issues.

**Comment by nadako** [comment]
Yeah I noticed sound issues too. Don't they happen on 3.2.1 as well  though?

**Comment by Memorix101** [comment]
On (stable release from haxe.org) 3.2.1 sounds worked well, but the player behavior was weird.

**Comment by nadako** [comment]
That's worrying, I'll look into it.

**Comment by nadako** [comment]
hmm, i'm getting the same behaviour when compiled with 3.2.1 - first shot sounds plays, but then silence (though music and ambient is still playing)

**Comment by Memorix101** [comment]
Yes, and the weird is with the version from haxe.org. Sounds are working, but the player isn't ... :/

**Comment by nadako** [comment]
strange - i tested with 3.2.1 from haxe.org and sound didn't work properly there as well. i'll look into it a bit later today

**Comment by nadako** [comment]
The sound problem seem to be the issue with Chrome and is also reproduced in original WebQuake: http://webquake.quaddicted.com/Client/index.htm Both work in Firefox for me and it doesn't depend on Haxe version or compilation options.

**Comment by nadako** [comment]
That is probably related to the fact webquake/haxequake are using obsolete synchronous data loading and it tries to play audio before it's loaded, or something like that. That should be changed to use async, but it's a huge refactoring I'm not ready yet to make.

**Comment by Memorix101** [comment]
Good to know its a Chrome issue :) ... Do you think there is a "easier" workaround for Chrome then pulling everything over to async :x

**Comment by nadako** [comment]
hmm, i can't reproduce it in webquake now... wtf is going on :)

**Comment by nadako** [comment]
nvm, i can
