### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by Memorix101** [nadako/HaxeQuake#8]
Hey,

Can you help me ?
I can't compile the code, I only get those errors :/

![rtrtztz](https://cloud.githubusercontent.com/assets/1466920/12325240/089aaf74-bac9-11e5-98eb-cb87c23d6aa8.PNG)

![screenshot 220](https://cloud.githubusercontent.com/assets/1466920/12325219/d7fa73c2-bac8-11e5-8681-4e6dd2dbb2fd.png)

**Comment by nadako** [comment]
That is probably I'm using some feature that is only available in development haxe version. I'm not sure what one exactly though. I'll look into whether it can be easily made compilable with 3.2 a bit later.

**Comment by Memorix101** [comment]
Thanks :)
I'm running 3.2.1

**Comment by nadako** [comment]
Yeah, that seems to be the `@:resolve` macro used in `EdictVars` which is only available in Haxe 3.3+. I think that's an overcomplication and I'll try changing that to a simple @:build macro

**Comment by nadako** [comment]
Okay, I made it compile with haxe 3.2.1. That required some changes to abstract build macros and a couple of other places. It seems to work \o/

**Comment by nadako** [comment]
I'm leaving this issue open because I actually use this project for playing with the compiler, and I'd like to setup Travis build that builds both 3.2.1 and latest dev version. I'll do that later today.

**Comment by Memorix101** [comment]
Yes it works :D Thanks ! :D

**Comment by nadako** [comment]
It won't compile again since I removed support because of https://github.com/nadako/HaxeQuake/issues/10#issuecomment-173174065
